title: Celia Wang
logo: /assets/images/logo.avif
baseurl: /W5-a11y/celia_portfolio.git

##
# Collections configuration
##
collections:
  projects:
    output: true
    permalink: /:collection/:name/

##
# Contact Channels configuration
# Uncomment for enable. Available contact channels are email, github, telegram, stackoverflow, discord, mastodon.
# Please fell free to send a PR if you need a new one.
# DISABLE GITHUB setting it as an empty string: ""
# if false, then no contact channels will be display.
##
contact_channels_section: true
contact_channels:
  email: "celia_wang@berkeley.edu"
  github: "https://github.com/W5-a11y"
  linkedin: "https://www.linkedin.com/in/celiawang19/"

##
# Plugins configuration
##
plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot

##
# Polyglot configuration
##
languages: ["en", "zh"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

##
# Archives configuration
##
jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"
